language: node_js
node_js:
- '0.8'
python:
- 2.7.6
ruby:
- 2.0.0
before_install:
- npm install -g grunt-cli
- bundle install
install: npm install
before_script: grunt build
deploy:
  provider: divshot
  skip_cleanup: true
  api_key:
    secure: tu4zBMiman7HE+gz5uUBgBYVYBGOTKAkMGAVC0rGheKtt9LrEi4j14zZ4htyg56uTI9KuabIpIJbqSIywXRTk6TcRzyi3FrSf2KiJtNykic3MiO0dbX6rbK43WQXFt5VjvJ7sujcOZEigDxnfKWQE+3AULRp2ysjNNzy6TNUyhN02zf8EbMDVghqVF9RbOwwp36Z/ZWyWOOzwzr+FhRcp6FBPmnd+2dH+mn2ziFb6FQqaSRaH6EkybsALkuqQ5VvXy1GNLWTzcSQMp4yYc+jw3AcTUJYkChanxq+baEX0O4tASgqeAa7ti8liR0TAc54zFTrzKR1Dv9ZMKGJb1RJqsELZHRTRi4In5bRAFtw6qI4mn4PasoYcx8oAoWKDJr4ddpAaMzSrqxcaknbuaKnqOt0TSXvv7Ap2G72lxtX83F31uQH80wBzIcJMu1tf6eKpLk8lf4AhEZ5mpeZCz7ccqIwiB7bSb82qOO4n5WP9LytXGmtMwMXa5I4PcRP5cT+POTxgd/NvhqzeszOjxpIC/pNj646qlsN1cz2va2C/ZvRtBhmQ+B5uRCuFGcuinuv60rLbje6DpcgoxfSjagJiwM420e7mro7hKoUKiKEgzSnN5UpFoiJD6s8JJgz81KWugT2Y5Nb0NPElXj+E4BXUitpv8Y5/OtUy84P84nM+Gc=
  environment: Production
  on:
    repo: stuart-bennett/openheartnerdery
